version: '3'

volumes:
  db_tooskie:

services:
  db:
    image: postgres:9.6
    environment:
      POSTGRES_USER: tooskie
      POSTGRES_PASSWORD: tooskie
      POSTGRES_DB: tooskie
    volumes:
      - db_tooskie:/var/lib/postgresql/data

  web:
    restart: always
    build: 
      context: .
      dockerfile: Dockerfile
    environment:
      DJANGO_CONFIGURATION: Local
      DJANGO_SETTINGS_MODULE: tooskie.config
    command: bash -c "sleep 10 && python3 manage.py makemigrations && python manage.py migrate && python3 manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/app
    ports:
      - "80:8000"
    depends_on:
      - db