version: '3'

volumes:
  db_tooskie:

services:
  db:
    image: postgres:9.6
    environment:
      POSTGRES_USER: tooskie
      POSTGRES_PASSWORD: tooskie
      POSTGRES_DB: tooskie
    volumes:
      - db_tooskie:/var/lib/postgresql/data

  myadmin:
    image: adminer
    environment:
      POSTGRES_USER: tooskie
      POSTGRES_PASSWORD: tooskie
      POSTGRES_DB: tooskie
    ports:
      - "8080:8080"
    depends_on:
      - db

  web:
    restart: always
    build: 
      context: .
      dockerfile: Dockerfile
    environment:
      DJANGO_CONFIGURATION: Local
      DJANGO_SETTINGS_MODULE: tooskie.config
      LOGGING_LEVEL: DEBUG
    command: bash -c "sleep 5 && python manage.py migrate && python manage.py makemigrations utils user recipe pantry shop && python manage.py migrate && python manage.py update_translation_fields && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/app
    ports:
      - "80:8000"
    depends_on:
      - db