# Generated by Django 2.1.1 on 2018-09-18 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permaname', models.SlugField(max_length=1000, unique=True, verbose_name='Permaname')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Last updated at')),
                ('name', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Name')),
                ('cooking_time', models.IntegerField(blank=True, null=True, verbose_name='Cooking time')),
                ('preparation_time', models.IntegerField(blank=True, null=True, verbose_name='Preparation time')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
